version: "3.7"

services:
      mysql: 
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sgpi_db
        ports:
          - 3307:3306
        volumes:
          - ./mysql:/var/lib/mysql

      # sgpi-api--node: 
      #   platform: linux/x86_64
      #   image: sgpi-api--node
      #   container_name: sgpi-api--node
      #   restart: always
      #   environment:
      #     MYSQL_HOST: mysql
      #     MYSQL_USER: root
      #     MYSQL_PASSWORD: password
      #     MYSQL_DB: sgpi_db
      #   ports:
      #     - 3000:3000

      # backend-report: 
      #   platform: linux/x86_64
      #   image: openjdk:11
      #   container_name: backend-report
      #   restart: always
      #   environment:
      #     MYSQL_HOST: mysql
      #     MYSQL_USER: root
      #     MYSQL_PASSWORD: password
      #     MYSQL_DB: sgpi_db
      #   ports:
      #     - 8081:8081