version: "3.7"

services:
      mysql: 
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        volumes:
          - ./mysql:/var/lib/mysql